package com.zstrength.usr.pojo;

// Generated Nov 26, 2014 9:13:25 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * UsrMembers generated by hbm2java
 */
public class UsrMembers implements java.io.Serializable {

	private String memberId;
	private int memberNumber;
	private String personalId;
	private String passwd;
	private String chineseName;
	private String mobile;
	private String email;
	private String homePhone;
	private String officePhone;
	private String faxNo;
	private String birthday;
	private String gender;
	private String marriedStatus;
	private String education;
	private String job;
	private String monthlyIncome;
	private char status;
	private String censusRegion;
	private String censusSection;
	private String censusStreet;
	private Integer censusAlley;
	private Integer censusLane;
	private Integer censusFloor;
	private String censusAddrNumber;
	private Integer censusSuite;
	private String comRegion;
	private String comSection;
	private String comStreet;
	private Integer comAlley;
	private Integer comLane;
	private Integer comFloor;
	private String comAddrNumber;
	private Integer comSuite;
	private Date updatedDatetime;
	private Date createdDatetime;
	private Date mobileValidatedDatetime;
	private Date emailValidatedDatetime;
	private String remark;

	public UsrMembers() {
	}

	public UsrMembers(int memberNumber, String personalId, String passwd,
			String mobile, String email, char status, Date createdDatetime) {
		this.memberNumber = memberNumber;
		this.personalId = personalId;
		this.passwd = passwd;
		this.mobile = mobile;
		this.email = email;
		this.status = status;
		this.createdDatetime = createdDatetime;
	}

	public UsrMembers(int memberNumber, String personalId, String passwd,
			String chineseName, String mobile, String email, String homePhone,
			String officePhone, String faxNo, String birthday, String gender,
			String marriedStatus, String education, String job,
			String monthlyIncome, char status, String censusRegion,
			String censusSection, String censusStreet, Integer censusAlley,
			Integer censusLane, Integer censusFloor, String censusAddrNumber,
			Integer censusSuite, String comRegion, String comSection,
			String comStreet, Integer comAlley, Integer comLane,
			Integer comFloor, String comAddrNumber, Integer comSuite,
			Date updatedDatetime, Date createdDatetime,
			Date mobileValidatedDatetime, Date emailValidatedDatetime,
			String remark) {
		this.memberNumber = memberNumber;
		this.personalId = personalId;
		this.passwd = passwd;
		this.chineseName = chineseName;
		this.mobile = mobile;
		this.email = email;
		this.homePhone = homePhone;
		this.officePhone = officePhone;
		this.faxNo = faxNo;
		this.birthday = birthday;
		this.gender = gender;
		this.marriedStatus = marriedStatus;
		this.education = education;
		this.job = job;
		this.monthlyIncome = monthlyIncome;
		this.status = status;
		this.censusRegion = censusRegion;
		this.censusSection = censusSection;
		this.censusStreet = censusStreet;
		this.censusAlley = censusAlley;
		this.censusLane = censusLane;
		this.censusFloor = censusFloor;
		this.censusAddrNumber = censusAddrNumber;
		this.censusSuite = censusSuite;
		this.comRegion = comRegion;
		this.comSection = comSection;
		this.comStreet = comStreet;
		this.comAlley = comAlley;
		this.comLane = comLane;
		this.comFloor = comFloor;
		this.comAddrNumber = comAddrNumber;
		this.comSuite = comSuite;
		this.updatedDatetime = updatedDatetime;
		this.createdDatetime = createdDatetime;
		this.mobileValidatedDatetime = mobileValidatedDatetime;
		this.emailValidatedDatetime = emailValidatedDatetime;
		this.remark = remark;
	}

	public String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	public int getMemberNumber() {
		return this.memberNumber;
	}

	public void setMemberNumber(int memberNumber) {
		this.memberNumber = memberNumber;
	}

	public String getPersonalId() {
		return this.personalId;
	}

	public void setPersonalId(String personalId) {
		this.personalId = personalId;
	}

	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	public String getChineseName() {
		return this.chineseName;
	}

	public void setChineseName(String chineseName) {
		this.chineseName = chineseName;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getHomePhone() {
		return this.homePhone;
	}

	public void setHomePhone(String homePhone) {
		this.homePhone = homePhone;
	}

	public String getOfficePhone() {
		return this.officePhone;
	}

	public void setOfficePhone(String officePhone) {
		this.officePhone = officePhone;
	}

	public String getFaxNo() {
		return this.faxNo;
	}

	public void setFaxNo(String faxNo) {
		this.faxNo = faxNo;
	}

	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getMarriedStatus() {
		return this.marriedStatus;
	}

	public void setMarriedStatus(String marriedStatus) {
		this.marriedStatus = marriedStatus;
	}

	public String getEducation() {
		return this.education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public String getMonthlyIncome() {
		return this.monthlyIncome;
	}

	public void setMonthlyIncome(String monthlyIncome) {
		this.monthlyIncome = monthlyIncome;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	public String getCensusRegion() {
		return this.censusRegion;
	}

	public void setCensusRegion(String censusRegion) {
		this.censusRegion = censusRegion;
	}

	public String getCensusSection() {
		return this.censusSection;
	}

	public void setCensusSection(String censusSection) {
		this.censusSection = censusSection;
	}

	public String getCensusStreet() {
		return this.censusStreet;
	}

	public void setCensusStreet(String censusStreet) {
		this.censusStreet = censusStreet;
	}

	public Integer getCensusAlley() {
		return this.censusAlley;
	}

	public void setCensusAlley(Integer censusAlley) {
		this.censusAlley = censusAlley;
	}

	public Integer getCensusLane() {
		return this.censusLane;
	}

	public void setCensusLane(Integer censusLane) {
		this.censusLane = censusLane;
	}

	public Integer getCensusFloor() {
		return this.censusFloor;
	}

	public void setCensusFloor(Integer censusFloor) {
		this.censusFloor = censusFloor;
	}

	public String getCensusAddrNumber() {
		return this.censusAddrNumber;
	}

	public void setCensusAddrNumber(String censusAddrNumber) {
		this.censusAddrNumber = censusAddrNumber;
	}

	public Integer getCensusSuite() {
		return this.censusSuite;
	}

	public void setCensusSuite(Integer censusSuite) {
		this.censusSuite = censusSuite;
	}

	public String getComRegion() {
		return this.comRegion;
	}

	public void setComRegion(String comRegion) {
		this.comRegion = comRegion;
	}

	public String getComSection() {
		return this.comSection;
	}

	public void setComSection(String comSection) {
		this.comSection = comSection;
	}

	public String getComStreet() {
		return this.comStreet;
	}

	public void setComStreet(String comStreet) {
		this.comStreet = comStreet;
	}

	public Integer getComAlley() {
		return this.comAlley;
	}

	public void setComAlley(Integer comAlley) {
		this.comAlley = comAlley;
	}

	public Integer getComLane() {
		return this.comLane;
	}

	public void setComLane(Integer comLane) {
		this.comLane = comLane;
	}

	public Integer getComFloor() {
		return this.comFloor;
	}

	public void setComFloor(Integer comFloor) {
		this.comFloor = comFloor;
	}

	public String getComAddrNumber() {
		return this.comAddrNumber;
	}

	public void setComAddrNumber(String comAddrNumber) {
		this.comAddrNumber = comAddrNumber;
	}

	public Integer getComSuite() {
		return this.comSuite;
	}

	public void setComSuite(Integer comSuite) {
		this.comSuite = comSuite;
	}

	public Date getUpdatedDatetime() {
		return this.updatedDatetime;
	}

	public void setUpdatedDatetime(Date updatedDatetime) {
		this.updatedDatetime = updatedDatetime;
	}

	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	public Date getMobileValidatedDatetime() {
		return this.mobileValidatedDatetime;
	}

	public void setMobileValidatedDatetime(Date mobileValidatedDatetime) {
		this.mobileValidatedDatetime = mobileValidatedDatetime;
	}

	public Date getEmailValidatedDatetime() {
		return this.emailValidatedDatetime;
	}

	public void setEmailValidatedDatetime(Date emailValidatedDatetime) {
		this.emailValidatedDatetime = emailValidatedDatetime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
