package com.zstrength.usr.pojo;

// Generated 2013/12/12 ?? 05:10:09 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * UsrMembers generated by hbm2java
 */
public class UsrMembers implements java.io.Serializable {

	private String memberId;
	private String personalId;
	private String passwd;
	private String chineseName;
	private String mobile;
	private String email;
	private String homePhone;
	private String officePhone;
	private String city;
	private String county;
	private String area;
	private String address1;
	private String address2;
	private String birthday;
	private String sex;
	private String status;
	private Date createdDatetime;
	private Date validatedDatetime;
	private Date updatedDatetime;
	private String remark;

	public UsrMembers() {
	}

	public UsrMembers(String memberId, String personalId, String passwd,
			String chineseName, String mobile, String status,
			Date createdDatetime) {
		this.memberId = memberId;
		this.personalId = personalId;
		this.passwd = passwd;
		this.chineseName = chineseName;
		this.mobile = mobile;
		this.status = status;
		this.createdDatetime = createdDatetime;
	}

	public UsrMembers(String memberId, String personalId, String passwd,
			String chineseName, String mobile, String email, String homePhone,
			String officePhone, String city, String county, String area,
			String address1, String address2, String birthday, String sex,
			String status, Date createdDatetime, Date validatedDatetime,
			Date updatedDatetime, String remark) {
		this.memberId = memberId;
		this.personalId = personalId;
		this.passwd = passwd;
		this.chineseName = chineseName;
		this.mobile = mobile;
		this.email = email;
		this.homePhone = homePhone;
		this.officePhone = officePhone;
		this.city = city;
		this.county = county;
		this.area = area;
		this.address1 = address1;
		this.address2 = address2;
		this.birthday = birthday;
		this.sex = sex;
		this.status = status;
		this.createdDatetime = createdDatetime;
		this.validatedDatetime = validatedDatetime;
		this.updatedDatetime = updatedDatetime;
		this.remark = remark;
	}

	public String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	public String getPersonalId() {
		return this.personalId;
	}

	public void setPersonalId(String personalId) {
		this.personalId = personalId;
	}

	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	public String getChineseName() {
		return this.chineseName;
	}

	public void setChineseName(String chineseName) {
		this.chineseName = chineseName;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getHomePhone() {
		return this.homePhone;
	}

	public void setHomePhone(String homePhone) {
		this.homePhone = homePhone;
	}

	public String getOfficePhone() {
		return this.officePhone;
	}

	public void setOfficePhone(String officePhone) {
		this.officePhone = officePhone;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	public Date getValidatedDatetime() {
		return this.validatedDatetime;
	}

	public void setValidatedDatetime(Date validatedDatetime) {
		this.validatedDatetime = validatedDatetime;
	}

	public Date getUpdatedDatetime() {
		return this.updatedDatetime;
	}

	public void setUpdatedDatetime(Date updatedDatetime) {
		this.updatedDatetime = updatedDatetime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
