package com.zstrength.usr.pojo;

// Generated 2013/12/12 ?? 05:10:09 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * UsrSocial generated by hbm2java
 */
public class UsrSocial implements java.io.Serializable {

	private String socialId;
	private String socialName;
	private int memberCount;
	private Date createdDatetime;
	private Date updatedDatetime;

	public UsrSocial() {
	}

	public UsrSocial(String socialId, String socialName, int memberCount,
			Date createdDatetime) {
		this.socialId = socialId;
		this.socialName = socialName;
		this.memberCount = memberCount;
		this.createdDatetime = createdDatetime;
	}

	public UsrSocial(String socialId, String socialName, int memberCount,
			Date createdDatetime, Date updatedDatetime) {
		this.socialId = socialId;
		this.socialName = socialName;
		this.memberCount = memberCount;
		this.createdDatetime = createdDatetime;
		this.updatedDatetime = updatedDatetime;
	}

	public String getSocialId() {
		return this.socialId;
	}

	public void setSocialId(String socialId) {
		this.socialId = socialId;
	}

	public String getSocialName() {
		return this.socialName;
	}

	public void setSocialName(String socialName) {
		this.socialName = socialName;
	}

	public int getMemberCount() {
		return this.memberCount;
	}

	public void setMemberCount(int memberCount) {
		this.memberCount = memberCount;
	}

	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	public Date getUpdatedDatetime() {
		return this.updatedDatetime;
	}

	public void setUpdatedDatetime(Date updatedDatetime) {
		this.updatedDatetime = updatedDatetime;
	}

}
