package com.zstrength.usr.pojo;

// Generated 2013/12/12 ?? 05:10:09 by Hibernate Tools 4.0.0

/**
 * UsrSocialMemberId generated by hbm2java
 */
public class UsrSocialMemberId implements java.io.Serializable {

	private String socialId;
	private int socialMemberSeq;

	public UsrSocialMemberId() {
	}

	public UsrSocialMemberId(String socialId, int socialMemberSeq) {
		this.socialId = socialId;
		this.socialMemberSeq = socialMemberSeq;
	}

	public String getSocialId() {
		return this.socialId;
	}

	public void setSocialId(String socialId) {
		this.socialId = socialId;
	}

	public int getSocialMemberSeq() {
		return this.socialMemberSeq;
	}

	public void setSocialMemberSeq(int socialMemberSeq) {
		this.socialMemberSeq = socialMemberSeq;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsrSocialMemberId))
			return false;
		UsrSocialMemberId castOther = (UsrSocialMemberId) other;

		return ((this.getSocialId() == castOther.getSocialId()) || (this
				.getSocialId() != null && castOther.getSocialId() != null && this
				.getSocialId().equals(castOther.getSocialId())))
				&& (this.getSocialMemberSeq() == castOther.getSocialMemberSeq());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSocialId() == null ? 0 : this.getSocialId().hashCode());
		result = 37 * result + this.getSocialMemberSeq();
		return result;
	}

}
