package com.zstrength.building.pojo;

// Generated Jun 24, 2015 4:52:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * BuildingEnterprises generated by hbm2java
 */
public class BuildingEnterprises implements java.io.Serializable {

	private Integer entId;
	private int buildingId;
	private String entName;
	private String floor;
	private String content;
	private String url;
	private String tel;
	private String logoUrl;
	private Boolean valid;
	private Integer createdId;
	private Date createdDatetime;

	public BuildingEnterprises() {
	}

	public BuildingEnterprises(int buildingId, String content) {
		this.buildingId = buildingId;
		this.content = content;
	}

	public BuildingEnterprises(int buildingId, String entName, String floor,
			String content, String url, String tel, String logoUrl,
			Boolean valid, Integer createdId, Date createdDatetime) {
		this.buildingId = buildingId;
		this.entName = entName;
		this.floor = floor;
		this.content = content;
		this.url = url;
		this.tel = tel;
		this.logoUrl = logoUrl;
		this.valid = valid;
		this.createdId = createdId;
		this.createdDatetime = createdDatetime;
	}

	public Integer getEntId() {
		return this.entId;
	}

	public void setEntId(Integer entId) {
		this.entId = entId;
	}

	public int getBuildingId() {
		return this.buildingId;
	}

	public void setBuildingId(int buildingId) {
		this.buildingId = buildingId;
	}

	public String getEntName() {
		return this.entName;
	}

	public void setEntName(String entName) {
		this.entName = entName;
	}

	public String getFloor() {
		return this.floor;
	}

	public void setFloor(String floor) {
		this.floor = floor;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getLogoUrl() {
		return this.logoUrl;
	}

	public void setLogoUrl(String logoUrl) {
		this.logoUrl = logoUrl;
	}

	public Boolean getValid() {
		return this.valid;
	}

	public void setValid(Boolean valid) {
		this.valid = valid;
	}

	public Integer getCreatedId() {
		return this.createdId;
	}

	public void setCreatedId(Integer createdId) {
		this.createdId = createdId;
	}

	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

}
