package com.zstrength.coupon.pojo;

// Generated Dec 3, 2014 8:43:59 AM by Hibernate Tools 4.3.1

/**
 * CouponGroupCodesId generated by hbm2java
 */
public class CouponGroupCodesId implements java.io.Serializable {

	private int groupId;
	private String couponCode;

	public CouponGroupCodesId() {
	}

	public CouponGroupCodesId(int groupId, String couponCode) {
		this.groupId = groupId;
		this.couponCode = couponCode;
	}

	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	public String getCouponCode() {
		return this.couponCode;
	}

	public void setCouponCode(String couponCode) {
		this.couponCode = couponCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CouponGroupCodesId))
			return false;
		CouponGroupCodesId castOther = (CouponGroupCodesId) other;

		return (this.getGroupId() == castOther.getGroupId())
				&& ((this.getCouponCode() == castOther.getCouponCode()) || (this
						.getCouponCode() != null
						&& castOther.getCouponCode() != null && this
						.getCouponCode().equals(castOther.getCouponCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGroupId();
		result = 37
				* result
				+ (getCouponCode() == null ? 0 : this.getCouponCode()
						.hashCode());
		return result;
	}

}
