package com.zstrength.coupon.pojo;

// Generated Dec 3, 2014 8:43:59 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * CouponGroupCodes generated by hbm2java
 */
public class CouponGroupCodes implements java.io.Serializable {

	private CouponGroupCodesId id;
	private String memberId;
	private String memberType;
	private Date createdDatetime;
	private Date updatedDatetime;
	private String remark;
	private Boolean used;

	public CouponGroupCodes() {
	}

	public CouponGroupCodes(CouponGroupCodesId id) {
		this.id = id;
	}

	public CouponGroupCodes(CouponGroupCodesId id, String memberId,
			String memberType, Date createdDatetime, Date updatedDatetime,
			String remark, Boolean used) {
		this.id = id;
		this.memberId = memberId;
		this.memberType = memberType;
		this.createdDatetime = createdDatetime;
		this.updatedDatetime = updatedDatetime;
		this.remark = remark;
		this.used = used;
	}

	public CouponGroupCodesId getId() {
		return this.id;
	}

	public void setId(CouponGroupCodesId id) {
		this.id = id;
	}

	public String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	public String getMemberType() {
		return this.memberType;
	}

	public void setMemberType(String memberType) {
		this.memberType = memberType;
	}

	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	public Date getUpdatedDatetime() {
		return this.updatedDatetime;
	}

	public void setUpdatedDatetime(Date updatedDatetime) {
		this.updatedDatetime = updatedDatetime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Boolean getUsed() {
		return this.used;
	}

	public void setUsed(Boolean used) {
		this.used = used;
	}

}
