package com.zstrength.basic.pojo;

// Generated May 18, 2015 12:06:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * BasicActualSellingBuildingInfos generated by hbm2java
 */
public class BasicActualSellingBuildingInfos implements java.io.Serializable {

	private Integer infoId;
	private String regNumber;
	private Integer ages;
	private Float totalSquareMeters;
	private String mainPurpose;
	private String mainMeterials;
	private String completedYearMonth;
	private Integer totalFloors;
	private String migrationFloor;
	private Date createdDatetime;
	private Date updatedDatetime;

	public BasicActualSellingBuildingInfos() {
	}

	public BasicActualSellingBuildingInfos(String regNumber, Integer ages,
			Float totalSquareMeters, String mainPurpose, String mainMeterials,
			String completedYearMonth, Integer totalFloors,
			String migrationFloor, Date createdDatetime, Date updatedDatetime) {
		this.regNumber = regNumber;
		this.ages = ages;
		this.totalSquareMeters = totalSquareMeters;
		this.mainPurpose = mainPurpose;
		this.mainMeterials = mainMeterials;
		this.completedYearMonth = completedYearMonth;
		this.totalFloors = totalFloors;
		this.migrationFloor = migrationFloor;
		this.createdDatetime = createdDatetime;
		this.updatedDatetime = updatedDatetime;
	}

	public Integer getInfoId() {
		return this.infoId;
	}

	public void setInfoId(Integer infoId) {
		this.infoId = infoId;
	}

	public String getRegNumber() {
		return this.regNumber;
	}

	public void setRegNumber(String regNumber) {
		this.regNumber = regNumber;
	}

	public Integer getAges() {
		return this.ages;
	}

	public void setAges(Integer ages) {
		this.ages = ages;
	}

	public Float getTotalSquareMeters() {
		return this.totalSquareMeters;
	}

	public void setTotalSquareMeters(Float totalSquareMeters) {
		this.totalSquareMeters = totalSquareMeters;
	}

	public String getMainPurpose() {
		return this.mainPurpose;
	}

	public void setMainPurpose(String mainPurpose) {
		this.mainPurpose = mainPurpose;
	}

	public String getMainMeterials() {
		return this.mainMeterials;
	}

	public void setMainMeterials(String mainMeterials) {
		this.mainMeterials = mainMeterials;
	}

	public String getCompletedYearMonth() {
		return this.completedYearMonth;
	}

	public void setCompletedYearMonth(String completedYearMonth) {
		this.completedYearMonth = completedYearMonth;
	}

	public Integer getTotalFloors() {
		return this.totalFloors;
	}

	public void setTotalFloors(Integer totalFloors) {
		this.totalFloors = totalFloors;
	}

	public String getMigrationFloor() {
		return this.migrationFloor;
	}

	public void setMigrationFloor(String migrationFloor) {
		this.migrationFloor = migrationFloor;
	}

	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	public Date getUpdatedDatetime() {
		return this.updatedDatetime;
	}

	public void setUpdatedDatetime(Date updatedDatetime) {
		this.updatedDatetime = updatedDatetime;
	}

}
