package com.zstrength.basic.pojo;

// Generated May 18, 2015 12:06:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * BasicActualSellingPrices generated by hbm2java
 */
public class BasicActualSellingPrices implements java.io.Serializable {

	private Integer regId;
	private String regType;
	private String city;
	private String cityCode;
	private String town;
	private String townCode;
	private String target;
	private String targetCode;
	private String address;
	private Float totalLandSquareMeters;
	private String cityAreaType;
	private String cityAreaTypeCode;
	private String nonCityAreaType;
	private String nonCityAreaTypeCode;
	private String nonCityAreaSetting;
	private String nonCityAreaSettingCode;
	private String txnYearMonth;
	private String txnYearMonthCe;
	private String txnCount;
	private Integer txnLandCount;
	private Integer txnBuildingCount;
	private Integer txnParkingCount;
	private String migrationFloor;
	private Integer totalFloors;
	private String buildingType;
	private String buildingTypeCode;
	private String mainPurpose;
	private String mainPurposeCode;
	private String mainMeterials;
	private String mainMeterialsCode;
	private String completedYearMonth;
	private String completedYearMonthCe;
	private Float totalBuildingSquareMeters;
	private Float layoutRoom;
	private Float layoutHall;
	private Float layoutBathroom;
	private Boolean layoutCompartment;
	private Boolean hasCmc;
	private Boolean hasFurniture;
	private Float totalPrice;
	private Float pricePerSquareMeters;
	private String parkingType;
	private String parkingTypeCode;
	private Float parkingTotalSquareMeters;
	private Float parkingPrice;
	private Double longitude;
	private Double latitude;
	private String remark;
	private String regNumber;
	private Date createdDatetime;
	private Date updatedDatetime;

	public BasicActualSellingPrices() {
	}

	public BasicActualSellingPrices(String regType) {
		this.regType = regType;
	}

	public BasicActualSellingPrices(String regType, String city,
			String cityCode, String town, String townCode, String target,
			String targetCode, String address, Float totalLandSquareMeters,
			String cityAreaType, String cityAreaTypeCode,
			String nonCityAreaType, String nonCityAreaTypeCode,
			String nonCityAreaSetting, String nonCityAreaSettingCode,
			String txnYearMonth, String txnYearMonthCe, String txnCount,
			Integer txnLandCount, Integer txnBuildingCount,
			Integer txnParkingCount, String migrationFloor,
			Integer totalFloors, String buildingType, String buildingTypeCode,
			String mainPurpose, String mainPurposeCode, String mainMeterials,
			String mainMeterialsCode, String completedYearMonth,
			String completedYearMonthCe, Float totalBuildingSquareMeters,
			Float layoutRoom, Float layoutHall, Float layoutBathroom,
			Boolean layoutCompartment, Boolean hasCmc, Boolean hasFurniture,
			Float totalPrice, Float pricePerSquareMeters, String parkingType,
			String parkingTypeCode, Float parkingTotalSquareMeters,
			Float parkingPrice, Double longitude, Double latitude,
			String remark, String regNumber, Date createdDatetime,
			Date updatedDatetime) {
		this.regType = regType;
		this.city = city;
		this.cityCode = cityCode;
		this.town = town;
		this.townCode = townCode;
		this.target = target;
		this.targetCode = targetCode;
		this.address = address;
		this.totalLandSquareMeters = totalLandSquareMeters;
		this.cityAreaType = cityAreaType;
		this.cityAreaTypeCode = cityAreaTypeCode;
		this.nonCityAreaType = nonCityAreaType;
		this.nonCityAreaTypeCode = nonCityAreaTypeCode;
		this.nonCityAreaSetting = nonCityAreaSetting;
		this.nonCityAreaSettingCode = nonCityAreaSettingCode;
		this.txnYearMonth = txnYearMonth;
		this.txnYearMonthCe = txnYearMonthCe;
		this.txnCount = txnCount;
		this.txnLandCount = txnLandCount;
		this.txnBuildingCount = txnBuildingCount;
		this.txnParkingCount = txnParkingCount;
		this.migrationFloor = migrationFloor;
		this.totalFloors = totalFloors;
		this.buildingType = buildingType;
		this.buildingTypeCode = buildingTypeCode;
		this.mainPurpose = mainPurpose;
		this.mainPurposeCode = mainPurposeCode;
		this.mainMeterials = mainMeterials;
		this.mainMeterialsCode = mainMeterialsCode;
		this.completedYearMonth = completedYearMonth;
		this.completedYearMonthCe = completedYearMonthCe;
		this.totalBuildingSquareMeters = totalBuildingSquareMeters;
		this.layoutRoom = layoutRoom;
		this.layoutHall = layoutHall;
		this.layoutBathroom = layoutBathroom;
		this.layoutCompartment = layoutCompartment;
		this.hasCmc = hasCmc;
		this.hasFurniture = hasFurniture;
		this.totalPrice = totalPrice;
		this.pricePerSquareMeters = pricePerSquareMeters;
		this.parkingType = parkingType;
		this.parkingTypeCode = parkingTypeCode;
		this.parkingTotalSquareMeters = parkingTotalSquareMeters;
		this.parkingPrice = parkingPrice;
		this.longitude = longitude;
		this.latitude = latitude;
		this.remark = remark;
		this.regNumber = regNumber;
		this.createdDatetime = createdDatetime;
		this.updatedDatetime = updatedDatetime;
	}

	public Integer getRegId() {
		return this.regId;
	}

	public void setRegId(Integer regId) {
		this.regId = regId;
	}

	public String getRegType() {
		return this.regType;
	}

	public void setRegType(String regType) {
		this.regType = regType;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCityCode() {
		return this.cityCode;
	}

	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}

	public String getTown() {
		return this.town;
	}

	public void setTown(String town) {
		this.town = town;
	}

	public String getTownCode() {
		return this.townCode;
	}

	public void setTownCode(String townCode) {
		this.townCode = townCode;
	}

	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	public String getTargetCode() {
		return this.targetCode;
	}

	public void setTargetCode(String targetCode) {
		this.targetCode = targetCode;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Float getTotalLandSquareMeters() {
		return this.totalLandSquareMeters;
	}

	public void setTotalLandSquareMeters(Float totalLandSquareMeters) {
		this.totalLandSquareMeters = totalLandSquareMeters;
	}

	public String getCityAreaType() {
		return this.cityAreaType;
	}

	public void setCityAreaType(String cityAreaType) {
		this.cityAreaType = cityAreaType;
	}

	public String getCityAreaTypeCode() {
		return this.cityAreaTypeCode;
	}

	public void setCityAreaTypeCode(String cityAreaTypeCode) {
		this.cityAreaTypeCode = cityAreaTypeCode;
	}

	public String getNonCityAreaType() {
		return this.nonCityAreaType;
	}

	public void setNonCityAreaType(String nonCityAreaType) {
		this.nonCityAreaType = nonCityAreaType;
	}

	public String getNonCityAreaTypeCode() {
		return this.nonCityAreaTypeCode;
	}

	public void setNonCityAreaTypeCode(String nonCityAreaTypeCode) {
		this.nonCityAreaTypeCode = nonCityAreaTypeCode;
	}

	public String getNonCityAreaSetting() {
		return this.nonCityAreaSetting;
	}

	public void setNonCityAreaSetting(String nonCityAreaSetting) {
		this.nonCityAreaSetting = nonCityAreaSetting;
	}

	public String getNonCityAreaSettingCode() {
		return this.nonCityAreaSettingCode;
	}

	public void setNonCityAreaSettingCode(String nonCityAreaSettingCode) {
		this.nonCityAreaSettingCode = nonCityAreaSettingCode;
	}

	public String getTxnYearMonth() {
		return this.txnYearMonth;
	}

	public void setTxnYearMonth(String txnYearMonth) {
		this.txnYearMonth = txnYearMonth;
	}

	public String getTxnYearMonthCe() {
		return this.txnYearMonthCe;
	}

	public void setTxnYearMonthCe(String txnYearMonthCe) {
		this.txnYearMonthCe = txnYearMonthCe;
	}

	public String getTxnCount() {
		return this.txnCount;
	}

	public void setTxnCount(String txnCount) {
		this.txnCount = txnCount;
	}

	public Integer getTxnLandCount() {
		return this.txnLandCount;
	}

	public void setTxnLandCount(Integer txnLandCount) {
		this.txnLandCount = txnLandCount;
	}

	public Integer getTxnBuildingCount() {
		return this.txnBuildingCount;
	}

	public void setTxnBuildingCount(Integer txnBuildingCount) {
		this.txnBuildingCount = txnBuildingCount;
	}

	public Integer getTxnParkingCount() {
		return this.txnParkingCount;
	}

	public void setTxnParkingCount(Integer txnParkingCount) {
		this.txnParkingCount = txnParkingCount;
	}

	public String getMigrationFloor() {
		return this.migrationFloor;
	}

	public void setMigrationFloor(String migrationFloor) {
		this.migrationFloor = migrationFloor;
	}

	public Integer getTotalFloors() {
		return this.totalFloors;
	}

	public void setTotalFloors(Integer totalFloors) {
		this.totalFloors = totalFloors;
	}

	public String getBuildingType() {
		return this.buildingType;
	}

	public void setBuildingType(String buildingType) {
		this.buildingType = buildingType;
	}

	public String getBuildingTypeCode() {
		return this.buildingTypeCode;
	}

	public void setBuildingTypeCode(String buildingTypeCode) {
		this.buildingTypeCode = buildingTypeCode;
	}

	public String getMainPurpose() {
		return this.mainPurpose;
	}

	public void setMainPurpose(String mainPurpose) {
		this.mainPurpose = mainPurpose;
	}

	public String getMainPurposeCode() {
		return this.mainPurposeCode;
	}

	public void setMainPurposeCode(String mainPurposeCode) {
		this.mainPurposeCode = mainPurposeCode;
	}

	public String getMainMeterials() {
		return this.mainMeterials;
	}

	public void setMainMeterials(String mainMeterials) {
		this.mainMeterials = mainMeterials;
	}

	public String getMainMeterialsCode() {
		return this.mainMeterialsCode;
	}

	public void setMainMeterialsCode(String mainMeterialsCode) {
		this.mainMeterialsCode = mainMeterialsCode;
	}

	public String getCompletedYearMonth() {
		return this.completedYearMonth;
	}

	public void setCompletedYearMonth(String completedYearMonth) {
		this.completedYearMonth = completedYearMonth;
	}

	public String getCompletedYearMonthCe() {
		return this.completedYearMonthCe;
	}

	public void setCompletedYearMonthCe(String completedYearMonthCe) {
		this.completedYearMonthCe = completedYearMonthCe;
	}

	public Float getTotalBuildingSquareMeters() {
		return this.totalBuildingSquareMeters;
	}

	public void setTotalBuildingSquareMeters(Float totalBuildingSquareMeters) {
		this.totalBuildingSquareMeters = totalBuildingSquareMeters;
	}

	public Float getLayoutRoom() {
		return this.layoutRoom;
	}

	public void setLayoutRoom(Float layoutRoom) {
		this.layoutRoom = layoutRoom;
	}

	public Float getLayoutHall() {
		return this.layoutHall;
	}

	public void setLayoutHall(Float layoutHall) {
		this.layoutHall = layoutHall;
	}

	public Float getLayoutBathroom() {
		return this.layoutBathroom;
	}

	public void setLayoutBathroom(Float layoutBathroom) {
		this.layoutBathroom = layoutBathroom;
	}

	public Boolean getLayoutCompartment() {
		return this.layoutCompartment;
	}

	public void setLayoutCompartment(Boolean layoutCompartment) {
		this.layoutCompartment = layoutCompartment;
	}

	public Boolean getHasCmc() {
		return this.hasCmc;
	}

	public void setHasCmc(Boolean hasCmc) {
		this.hasCmc = hasCmc;
	}

	public Boolean getHasFurniture() {
		return this.hasFurniture;
	}

	public void setHasFurniture(Boolean hasFurniture) {
		this.hasFurniture = hasFurniture;
	}

	public Float getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(Float totalPrice) {
		this.totalPrice = totalPrice;
	}

	public Float getPricePerSquareMeters() {
		return this.pricePerSquareMeters;
	}

	public void setPricePerSquareMeters(Float pricePerSquareMeters) {
		this.pricePerSquareMeters = pricePerSquareMeters;
	}

	public String getParkingType() {
		return this.parkingType;
	}

	public void setParkingType(String parkingType) {
		this.parkingType = parkingType;
	}

	public String getParkingTypeCode() {
		return this.parkingTypeCode;
	}

	public void setParkingTypeCode(String parkingTypeCode) {
		this.parkingTypeCode = parkingTypeCode;
	}

	public Float getParkingTotalSquareMeters() {
		return this.parkingTotalSquareMeters;
	}

	public void setParkingTotalSquareMeters(Float parkingTotalSquareMeters) {
		this.parkingTotalSquareMeters = parkingTotalSquareMeters;
	}

	public Float getParkingPrice() {
		return this.parkingPrice;
	}

	public void setParkingPrice(Float parkingPrice) {
		this.parkingPrice = parkingPrice;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getRegNumber() {
		return this.regNumber;
	}

	public void setRegNumber(String regNumber) {
		this.regNumber = regNumber;
	}

	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	public Date getUpdatedDatetime() {
		return this.updatedDatetime;
	}

	public void setUpdatedDatetime(Date updatedDatetime) {
		this.updatedDatetime = updatedDatetime;
	}

}
