package com.zstrength.basic.pojo;

// Generated May 18, 2015 12:06:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * BasicActualSellingParkingInfos generated by hbm2java
 */
public class BasicActualSellingParkingInfos implements java.io.Serializable {

	private Integer infoId;
	private String regNumber;
	private String parkingType;
	private Float parkingPrice;
	private Float totalSquareMeters;
	private Date createdDatetime;
	private Date updatedDatetime;

	public BasicActualSellingParkingInfos() {
	}

	public BasicActualSellingParkingInfos(String regNumber, String parkingType,
			Float parkingPrice, Float totalSquareMeters, Date createdDatetime,
			Date updatedDatetime) {
		this.regNumber = regNumber;
		this.parkingType = parkingType;
		this.parkingPrice = parkingPrice;
		this.totalSquareMeters = totalSquareMeters;
		this.createdDatetime = createdDatetime;
		this.updatedDatetime = updatedDatetime;
	}

	public Integer getInfoId() {
		return this.infoId;
	}

	public void setInfoId(Integer infoId) {
		this.infoId = infoId;
	}

	public String getRegNumber() {
		return this.regNumber;
	}

	public void setRegNumber(String regNumber) {
		this.regNumber = regNumber;
	}

	public String getParkingType() {
		return this.parkingType;
	}

	public void setParkingType(String parkingType) {
		this.parkingType = parkingType;
	}

	public Float getParkingPrice() {
		return this.parkingPrice;
	}

	public void setParkingPrice(Float parkingPrice) {
		this.parkingPrice = parkingPrice;
	}

	public Float getTotalSquareMeters() {
		return this.totalSquareMeters;
	}

	public void setTotalSquareMeters(Float totalSquareMeters) {
		this.totalSquareMeters = totalSquareMeters;
	}

	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	public Date getUpdatedDatetime() {
		return this.updatedDatetime;
	}

	public void setUpdatedDatetime(Date updatedDatetime) {
		this.updatedDatetime = updatedDatetime;
	}

}
