package com.zstrength.basic.pojo;

// Generated May 18, 2015 12:06:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * BasicActualSellingLandInfos generated by hbm2java
 */
public class BasicActualSellingLandInfos implements java.io.Serializable {

	private Integer infoId;
	private String regNumber;
	private String section;
	private Float totalSquareMeters;
	private String usageSetting;
	private Date createdDatetime;
	private Date updatedDatetime;

	public BasicActualSellingLandInfos() {
	}

	public BasicActualSellingLandInfos(String regNumber, String section,
			Float totalSquareMeters, String usageSetting, Date createdDatetime,
			Date updatedDatetime) {
		this.regNumber = regNumber;
		this.section = section;
		this.totalSquareMeters = totalSquareMeters;
		this.usageSetting = usageSetting;
		this.createdDatetime = createdDatetime;
		this.updatedDatetime = updatedDatetime;
	}

	public Integer getInfoId() {
		return this.infoId;
	}

	public void setInfoId(Integer infoId) {
		this.infoId = infoId;
	}

	public String getRegNumber() {
		return this.regNumber;
	}

	public void setRegNumber(String regNumber) {
		this.regNumber = regNumber;
	}

	public String getSection() {
		return this.section;
	}

	public void setSection(String section) {
		this.section = section;
	}

	public Float getTotalSquareMeters() {
		return this.totalSquareMeters;
	}

	public void setTotalSquareMeters(Float totalSquareMeters) {
		this.totalSquareMeters = totalSquareMeters;
	}

	public String getUsageSetting() {
		return this.usageSetting;
	}

	public void setUsageSetting(String usageSetting) {
		this.usageSetting = usageSetting;
	}

	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	public Date getUpdatedDatetime() {
		return this.updatedDatetime;
	}

	public void setUpdatedDatetime(Date updatedDatetime) {
		this.updatedDatetime = updatedDatetime;
	}

}
