package com.zstrength.event.pojo;
// Generated Mar 28, 2017 3:58:47 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * EventAds generated by hbm2java
 */
public class EventAds implements java.io.Serializable {

	private Integer adId;
	private String adTitle;
	private int adType;
	private int presentation;
	private int media;
	private String mediaDescript;
	private String ta;
	private Integer budget;
	private String goal;
	private boolean isClosed;
	private Date startDatetime;
	private Date endDatetime;
	private String adUrl;
	private String shortUrl;
	private int employeeId;
	private Date updatedDatetime;
	private Date createdDatetime;

	public EventAds() {
	}

	public EventAds(int adType, int presentation, int media, String ta, boolean isClosed, int employeeId) {
		this.adType = adType;
		this.presentation = presentation;
		this.media = media;
		this.ta = ta;
		this.isClosed = isClosed;
		this.employeeId = employeeId;
	}

	public EventAds(String adTitle, int adType, int presentation, int media, String mediaDescript, String ta,
			Integer budget, String goal, boolean isClosed, Date startDatetime, Date endDatetime, String adUrl,
			String shortUrl, int employeeId, Date updatedDatetime, Date createdDatetime) {
		this.adTitle = adTitle;
		this.adType = adType;
		this.presentation = presentation;
		this.media = media;
		this.mediaDescript = mediaDescript;
		this.ta = ta;
		this.budget = budget;
		this.goal = goal;
		this.isClosed = isClosed;
		this.startDatetime = startDatetime;
		this.endDatetime = endDatetime;
		this.adUrl = adUrl;
		this.shortUrl = shortUrl;
		this.employeeId = employeeId;
		this.updatedDatetime = updatedDatetime;
		this.createdDatetime = createdDatetime;
	}

	public Integer getAdId() {
		return this.adId;
	}

	public void setAdId(Integer adId) {
		this.adId = adId;
	}

	public String getAdTitle() {
		return this.adTitle;
	}

	public void setAdTitle(String adTitle) {
		this.adTitle = adTitle;
	}

	public int getAdType() {
		return this.adType;
	}

	public void setAdType(int adType) {
		this.adType = adType;
	}

	public int getPresentation() {
		return this.presentation;
	}

	public void setPresentation(int presentation) {
		this.presentation = presentation;
	}

	public int getMedia() {
		return this.media;
	}

	public void setMedia(int media) {
		this.media = media;
	}

	public String getMediaDescript() {
		return this.mediaDescript;
	}

	public void setMediaDescript(String mediaDescript) {
		this.mediaDescript = mediaDescript;
	}

	public String getTa() {
		return this.ta;
	}

	public void setTa(String ta) {
		this.ta = ta;
	}

	public Integer getBudget() {
		return this.budget;
	}

	public void setBudget(Integer budget) {
		this.budget = budget;
	}

	public String getGoal() {
		return this.goal;
	}

	public void setGoal(String goal) {
		this.goal = goal;
	}

	public boolean isIsClosed() {
		return this.isClosed;
	}

	public void setIsClosed(boolean isClosed) {
		this.isClosed = isClosed;
	}

	public Date getStartDatetime() {
		return this.startDatetime;
	}

	public void setStartDatetime(Date startDatetime) {
		this.startDatetime = startDatetime;
	}

	public Date getEndDatetime() {
		return this.endDatetime;
	}

	public void setEndDatetime(Date endDatetime) {
		this.endDatetime = endDatetime;
	}

	public String getAdUrl() {
		return this.adUrl;
	}

	public void setAdUrl(String adUrl) {
		this.adUrl = adUrl;
	}

	public String getShortUrl() {
		return this.shortUrl;
	}

	public void setShortUrl(String shortUrl) {
		this.shortUrl = shortUrl;
	}

	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	public Date getUpdatedDatetime() {
		return this.updatedDatetime;
	}

	public void setUpdatedDatetime(Date updatedDatetime) {
		this.updatedDatetime = updatedDatetime;
	}

	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

}
